### ISSUE TITLE
Some of the movies and tv shows does not exists.

### ISSUE THREAD

**Issue by sikander804** [pierrevano/whatson-api#4]
i am fetching `Parthenope (2024)` with imdb id `tt23853982` but the item is not found, and there are other movies and tv shows as well with the same error.

**Comment by pierrevano** [comment]
Hi, thank you for reporting this. Could you please share the movies/TV shows that do not exist yet?
For your information, I'm checking if the movie and/or TV show is released in France before making it available on the API.
For example, Parthenope will be released in France in 2025: https://www.allocine.fr/film/fichefilm_gen_cfilm=317554.html
